---
version: "2"
checks:
  file-lines:
    config:
      # The there is a correlation between the files CodeClimate rates the
      # worst and the biggest biggest files.
      #
      # I am trying to prioritize the files with the most problems, so
      # I chose a threshold that seems to accomplish this.
      #
      # Sorting https://codeclimate.com/github/rubygems/rubygems/code
      # by "lines of code" and "maintainability" can be useful to find
      # these correlations.
      #
      # - @duckinator
      threshold: 400
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: false
exclude_patterns:
- bundler/bundler.gemspec
- "bundler/*.md"
- bundler/lib/bundler/ssl_certs/*.pem
- bundler/lib/bundler/vendor/**/*
- bundler/lib/bundler/templates/**/*.tt
- bundler/man/*
- bundler/spec/**/*
- bundler/Rakefile
- test/**/*
- lib/rubygems/optparse.rb
- lib/rubygems/optparse/**/*
- lib/rubygems/tsort/**/*
