---
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: false
exclude_patterns:
- bundler/bundler.gemspec
- "bundler/*.md"
- bundler/lib/bundler/ssl_certs/*.pem
- bundler/lib/bundler/vendor/**/*
- bundler/lib/bundler/templates/**/*.tt
- bundler/man/*
- bundler/spec/**/*
- bundler/Rakefile
- test/**/*
- lib/rubygems/optparse.rb
- lib/rubygems/optparse/**/*
- lib/rubygems/tsort/**/*
